### PR TITLE
Added nmos-security mdns type

### PR DESCRIPTION
**Pull request by dannymeloy**

### CODE REVIEW

**Review by andrewbonney — COMMENTED** [review]
Looks like the tests need updating. Otherwise you'll need to bump the version and make a note in the changelog.

**Comment by simonrankine** [comment]
As Andrew said, but otherwise LGTM

**Comment by dannymeloy** [comment]
The tests pass as is, but I still need to add security-specific testing. 
NB - I left the "deps-required" in setup.py

**Comment by andrewbonney** [comment]
@dannymeloy just needs the version bump in the RPM specfile and I think we can merge it.

**Review by andrewbonney — APPROVED** [review]

**Pull request merged**
